import {TensorLexResult, TrainConfig, TrainingData, cosineSimilarity, createEmbeddingModel, loadModel, predictMatches, saveModel, trainModel} from './Tensorlex';
import {
  Preprocessor,
  bulkPreprocess,
  chainPreprocessors,
  convertToLowercase,
  expandAbbreviations,
  expandNumbers,
  numberToWords,
  removeConsecutiveSpaces,
  removeEmails,
  removeNonASCII,
  removeNumbers,
  removeSpecialCharacters,
  replaceAccentedChars,
  separateLetterFromNumber,
  shortenRepeatedChars,
  trimWhitespace,
  urlToPlaceholder,
} from './Preprocessors';
export {TensorLexResult, TrainConfig, TrainingData, cosineSimilarity, createEmbeddingModel, loadModel, predictMatches, saveModel, trainModel};
export {
  Preprocessor,
  bulkPreprocess,
  chainPreprocessors,
  convertToLowercase,
  expandAbbreviations,
  expandNumbers,
  numberToWords,
  removeConsecutiveSpaces,
  removeEmails,
  removeNonASCII,
  removeNumbers,
  removeSpecialCharacters,
  replaceAccentedChars,
  separateLetterFromNumber,
  shortenRepeatedChars,
  trimWhitespace,
  urlToPlaceholder,
};
